export const PREDEFINED_FIELDS = [
    "Computer Science",
    "Artificial Intelligence",
    "Data Science",
    "Machine Learning",
    "Software Engineering",
    "Cybersecurity",
    "Blockchain",
    "Cloud Computing",
    "Human-Computer Interaction",
    "Internet of Things",
    "Robotics",
    "Web Development",
    "Mobile Development",
    "Database Systems",
    "Networking",
    "Operating Systems",
    "Algorithms",
    "Computational Biology",
    "Quantum Computing",
    "Embedded Systems",
    "Game Development",
    "Data Analytics",
    "Augmented Reality",
    "Virtual Reality",
    "Natural Language Processing",
    "Computer Vision"
];
